export enum Languages{
    'JavaScript',
    'TypeScript',
    'C#',
    'HTML, CSS, JS',
    'Python',
    'C++',
    'Java',
    'CoffeeScript',
    'C',
    'F#',
    'Clojure',
    'Haskell',
    'Kotlin',
    'QBasic',
    'Forth',
    'LOLCODE',
    'BrainF',
    'Emoticon',
    'Bloop',
    'Unlambda',
    'Scheme',
    'APL',
    'Lua',
    'Ruby',
    'Roy',
    'Node.js',
    'Deno(beta)',
    'Golang',
    'Rust',
    'Swift',
    'Basic(beta)',
    'R',
    'Bash',
    'Crystal',
    'Julia',
    'Elixir',
    'Nim',
    'Dart',
    'Reason Node.js',
    'Tcl',
    'Erlang',
    'Pygame',
    'Love2D',
    'Emacs Lisp(Elisp)',
    'PHP Web Server',
    'SQLite',
    'PHP CLI',
    'Pyxel',
    'Raku',
    'Scala(beta)',
    'Nix(beta)',
    'Python(with Turtle)'
}
