name: Code Analysis
on:
  push:
    branches: [ main, dev ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main, dev ]
jobs:
  analyze_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install packages and lint Angular
        run: |
          cd frontend
          npm ci
          npm run lint
 
